# Generated by Django 3.0.2 on 2020-01-30 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like_voters',
            field=models.ManyToManyField(blank=True, related_name='like_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='unlike_voters',
            field=models.ManyToManyField(blank=True, related_name='unlike_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
