# Generated by Django 3.0.2 on 2020-01-30 21:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_auto_20200130_2043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsComment',
            new_name='Comment',
        ),
    ]
