# Generated by Django 3.0.2 on 2020-01-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='getintouch',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
