# Generated by Django 3.0.2 on 2020-01-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200131_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
