# Generated by Django 3.0.2 on 2020-01-30 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
                'ordering': ('profile_name',),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('stages_of_treatment', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('interesting_facts', models.CharField(max_length=250)),
                ('work_experience', models.CharField(max_length=50)),
                ('hobbies', models.CharField(max_length=100)),
                ('quote', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('facebook_link', models.CharField(blank=True, max_length=100)),
                ('instagram_link', models.CharField(blank=True, max_length=100)),
                ('linkedin_link', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aboutus.DoctorProfile')),
                ('specializations', models.ManyToManyField(related_name='doctors', to='aboutus.Specialization')),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
    ]
