# Generated by Django 3.0.2 on 2020-01-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aboutus.DoctorProfile'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
