# Generated by Django 3.0.2 on 2020-01-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_auto_20200125_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
