# Generated by Django 3.0.2 on 2020-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20200125_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='interesting_facts',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='work_experience',
            field=models.CharField(max_length=50),
        ),
    ]
