# Generated by Django 3.0.2 on 2020-01-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_auto_20200125_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(related_name='doctors', to='aboutus.Specialization'),
        ),
    ]
