# Generated by Django 3.0.2 on 2020-01-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_auto_20200125_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
