# Generated by Django 3.0.2 on 2020-01-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_auto_20200126_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='stages_of_treatment',
            field=models.TextField(blank=True),
        ),
    ]
